### ISSUE TITLE
Optional<int>.Missing == null returns null

### ISSUE THREAD

**Issue by DanTup** [ProductiveRage/Bridge.Immutable#1]
var a = Optional<int>.Missing;
    Console.Log(a == null ? "was null" : "was not null"); // outputs "was not null"
    Console.Log(a == null); // outputs *null*

`IsDefined` returns false as expected, it just seems to be the comparison to null that's bad. Using `IsDefined` for now as a workaround.

**Comment by ProductiveRage** [comment]
I think that this is a problem with Bridge.NET, I have raised the following bug report in their forum: http://forums.bridge.net/forum/bridge-net-pro/bugs/1391-comparing-struct-with-overridden-equals-method-to-null-returns-null-incorrectly

**Comment by ProductiveRage** [comment]
The bug has been fixed in Bridge.NET and so fixed here by bumping the Bridge dependency version up to 1.10.4 (the ProductiveRage.Immutable NuGet package now declares 1.10.4 as the min version).
