### ISSUE TITLE
Regular expression to match getters for ImmutabilityHelpers.ConstructSetter doesn't match

### ISSUE THREAD

**Issue by Porl91** [ProductiveRage/Bridge.Immutable#4]
Here's a sample of the issue:
http://deck.net/cdeaefb409b15c9b339bc4e401e7fc79

If you look in the output you can see that lines 29 and 32 differ, as 'i' is defined in the class 'T' and the interface 'IT' and because of this collision the class 'T' has given the getters / setters of 'i' an alias which doesn't match any of the regular expressions in ImmutabilityHelpers.ConstructSetter, meaning that when I attempt to set a property on this interface from a call to .With() it's throwing the following console error:

"The specified propertyIdentifier function did not match the expected format - must be a simple property get, such as \"function(_) { return _.getName(); }\", rather than..."

Danny mentioned perhaps relaxing / removing the regex that matches these generated function names and just rely on Bridge generating them correctly?

**Comment by ProductiveRage** [comment]
v1.9.8 will fix this and is currently being indexed by NuGet.org (so should be available within a few minutes)

**Comment by ProductiveRage** [comment]
This now works, where a class is cast to an interface and the "With" methods used:

	using System;
	using Bridge.Html5;
	using ProductiveRage.Immutable;

	namespace ClassLibrary1
	{
		public static class Program
		{
			[Ready]
			public static void Main()
			{
				Console.WriteLine("Hi!");

				var directPerson = new PersonDetails(1, "test");
				Console.WriteLine(directPerson.Name);
				directPerson = directPerson.With(_ => _.Name, "test2");
				Console.WriteLine(directPerson.Name);

				IAmImmutableAndHaveName viaInterfacePerson = new PersonDetails(1, "test");
				Console.WriteLine(viaInterfacePerson.Name);
				viaInterfacePerson = viaInterfacePerson.With(_ => _.Name, "test2");
				Console.WriteLine(viaInterfacePerson.Name);
			}
		}

		public sealed class PersonDetails : IAmImmutableAndHaveName
		{
			public PersonDetails(int key, string name)
			{
				this.CtorSet(_ => _.Key, key);
				this.CtorSet(_ => _.Name, name);
			}

			public int Key { get; }
			public string Name { get; }
		}

		public interface IAmImmutableAndHaveName : IAmImmutable
		{
			string Name { get; }
		}
	}
