### ISSUE TITLE
Analyser suggestion for IAmImmutable.With methods

### ISSUE THREAD

**Issue by Porl91** [ProductiveRage/Bridge.Immutable#6]
It's possible to provide IAmImmutable.With method overloads with values that can cause runtime errors due to it not being able to infer the desired type from the usage. For example, the following method signature:

```
public static T With<T, TPropertyValue>(this T source, Func<T, TPropertyValue> propertyIdentifier, TPropertyValue value) where T : IAmImmutable
```

If the 'TPropertyValue' of the value is of a less derived type (e.g. 'Object') than the return type of 'propertyIdentifier' (e.g. 'NonBlankTrimmedString') then the compiler won't complain, although you could for example be setting a NonBlankTrimmedString to an Object.

Here's a dotnetfiddle to demonstrate the issue in a smaller case:
https://dotnetfiddle.net/xAiJMx

Perhaps it would be worth writing an analyser to ensure that when calling these methods that the return type of the lambda is the same as the value that we're attempting to set and not a less derived type.

**Comment by ProductiveRage** [comment]
Sorry, I can't follow this. Will you include a min repro case in the form of Bridge code that illustrates what you mean?

**Comment by Porl91** [comment]
Yeah sure, here's a simple Bridge example:

``
using Bridge;
using Bridge.Html5;
using ProductiveRage.Immutable;

namespace BridgeApp
{
	public class App
	{
		[Ready]
		public static void Main(string[] args)
		{
			var test = new Test("value").With(_ => _.Value, new object());
			test.Value.Trim(); // This will cause a runtime error
		}
	}

	class Test : IAmImmutable
	{
		public Test(string value)
		{
			this.CtorSet(_ => _.Value, value);
		}

		public string Value { get; }
	}
}
``

**Comment by ProductiveRage** [comment]
The latest version of the NuGet package (1.11.4) will now test for this and emit the following error:

> TPropertyValue is a type that is less specialised than the indicated property (if the indicated property is a string, for example, then TPropertyValue may not be Object - TPropertyValue must match the property type precisely or be a type derived from it)
