### ISSUE TITLE
NonNullList funkiness when using KeyValuePair<TKey,TValue> as its generic type

### ISSUE THREAD

**Issue by dionrhys** [ProductiveRage/Bridge.Immutable#7]
I'm not able to properly store `KeyValuePair<TKey,TValue>` elements inside a `NonNullList<T>`. Accessing an element's Key or Value property produces very funky behaviour.

Min repro code:
```
using ProductiveRage.Immutable;
using System;
using System.Collections.Generic;

namespace NonNullListFunkyStructMinRepro
{
    public class App
    {
        public static void Main()
        {
            var item = new KeyValuePair<string, string>("abc", "def");
            Console.WriteLine(item);

            var list = NonNullList<KeyValuePair<string, string>>.Empty;
            list = list.Add(item);
            Console.WriteLine(list[0]);
        }
    }
}
```

The first Console.WriteLine call emits as expected:
```
[abc, def]
```

The second Console.WriteLine should do the same, but it instead prints this:
```
[function (key, value) {
                if (key === undefined) {
                    key = Bridge.getDefaultValue(TKey);
                }

                if (value === undefined) {
                    value = Bridge.getDefaultValue(TValue);
                }

                this.$initialize();
                this.key = key;
                this.value = value;
            }, ]
```

And the output from using the browser's console with the underlying JS directly:
```
> item
Object { $initialized: core.emptyFn(), key: "abc", value: "def" }
> list.getItem(0)
Object { $initialized: core.emptyFn(), key: .ctor(key, value), value: null, $$fullname: "System.Collections.Generic.KeyValue…", $kind: "struct", $$name: "System.Collections.Generic.KeyValue…" }
```

Things to note:
- `KeyValuePair<TKey, TValue>` is a struct
- This behaviour doesn't happen when I have my own custom generic struct (`MyStruct<TKey, TValue>`) that has getter-only Key and Value properties
- Other plains structs like `DateTime` work fine
- Similar behaviour happens when using `KeyValuePair<int, int>`, though `list[0].Value` then seems to emit 0 instead of nothing, making it seem like it just emits the default value for the expected type.

Given that `NonNullList<T>` works well with custom generic structs, it looks like there's some magic going on with Bridge's `KeyValuePair<TKey,TValue>` implementation.

**Comment by ProductiveRage** [comment]
Strange that it works for other structs for you, I get the same problem if I use custom structs! eg.

```
using System;
using Bridge.Html5;
using ProductiveRage.Immutable;

namespace Tester
{
	public static class Class1
	{
		[Ready]
		static void Main()
		{
			Console.WriteLine("HI!");

			var item = new MyKeyValuePair<string, string>("abc", "def");
			Console.WriteLine(item.Key);

			var list = NonNullList.Of(item);
			Console.WriteLine(list[0].Key);

			var retrievedItem = list[0];
			Console.WriteLine(retrievedItem.Key);
		}
	}

	public struct MyKeyValuePair<TKey, TValue>
	{
		public MyKeyValuePair(TKey key, TValue value)
		{
			Key = key;
			Value = value;
		}
		public TKey Key { get; }
		public TValue Value { get; }
	}
}
```

**Comment by ProductiveRage** [comment]
Confirmed that this is a Bridge bug (see [forums.bridge.net/forum/bridge-net-pro/bugs/3947-generic-type-issue-with-struct-encountered](https://forums.bridge.net/forum/bridge-net-pro/bugs/3947-generic-type-issue-with-struct-encountered)). The good news is that it's already fixed in their main branch. The bad news is that I have no idea when this will be released (I asked in that bug report but no answer is forthcoming yet),

**Comment by ProductiveRage** [comment]
The version of Bridge that addresses this should be getting released to a beta test period early next week. So hopefully it will be possible to close this issue soon!

**Comment by ProductiveRage** [comment]
Bridge 16 fixes this but it's been in beta forever, don't think there's much point leaving this issue open any longer!
